/* AUTO-GENERATED by tools/build-galleries.py — do not edit by hand.
   Maps species key -> ordered gallery image paths (cover first). */
window.GALLERY = {
  "trout-salmon": [
    "images/fish/trout-salmon.jpg",
    "images/fish/trout-salmon/w01.png",
    "images/fish/trout-salmon/w02.jpg",
    "images/fish/trout-salmon/w03.jpg",
    "images/fish/trout-salmon/w04.jpg"
  ],
  "atlantic-salmon": [
    "images/fish/atlantic-salmon.jpg",
    "images/fish/atlantic-salmon/u01.jpg",
    "images/fish/atlantic-salmon/u02.webp",
    "images/fish/atlantic-salmon/u03.jpg",
    "images/fish/atlantic-salmon/u04.webp",
    "images/fish/atlantic-salmon/u05.png"
  ],
  "largemouth-bass": [
    "images/fish/largemouth-bass.jpg",
    "images/fish/largemouth-bass/w01.jpg",
    "images/fish/largemouth-bass/w02.jpg",
    "images/fish/largemouth-bass/w03.jpg",
    "images/fish/largemouth-bass/w04.jpg"
  ],
  "smallmouth-bass": [
    "images/fish/smallmouth-bass.jpg",
    "images/fish/smallmouth-bass/w01.jpg",
    "images/fish/smallmouth-bass/w02.jpg",
    "images/fish/smallmouth-bass/w03.jpg",
    "images/fish/smallmouth-bass/w04.jpg"
  ],
  "bass-combined": [
    "images/fish/bass-combined.jpg",
    "images/fish/bass-combined/w01.jpg",
    "images/fish/bass-combined/w02.jpg",
    "images/fish/bass-combined/w03.jpg",
    "images/fish/bass-combined/w04.jpg"
  ],
  "brook-trout": [
    "images/fish/brook-trout.jpg",
    "images/fish/brook-trout/w01.jpg",
    "images/fish/brook-trout/w02.jpg",
    "images/fish/brook-trout/w03.jpg",
    "images/fish/brook-trout/w04.jpg"
  ],
  "brown-trout": [
    "images/fish/brown-trout.jpg",
    "images/fish/brown-trout/u01.jpg",
    "images/fish/brown-trout/u02.webp",
    "images/fish/brown-trout/u03.jpg",
    "images/fish/brown-trout/u04.jpg",
    "images/fish/brown-trout/u05.jpg",
    "images/fish/brown-trout/u06.jpg"
  ],
  "rainbow-trout": [
    "images/fish/rainbow-trout.jpg",
    "images/fish/rainbow-trout/w01.png",
    "images/fish/rainbow-trout/w02.jpg",
    "images/fish/rainbow-trout/w03.jpg",
    "images/fish/rainbow-trout/w04.jpg"
  ],
  "lake-trout": [
    "images/fish/lake-trout.jpg",
    "images/fish/lake-trout/u01.jpg",
    "images/fish/lake-trout/u02.jpg",
    "images/fish/lake-trout/u03.jpg",
    "images/fish/lake-trout/u04.jpg",
    "images/fish/lake-trout/u05.jpg"
  ],
  "splake": [
    "images/fish/splake.jpg",
    "images/fish/splake/w01.jpg",
    "images/fish/splake/w02.jpg"
  ],
  "chinook-salmon": [
    "images/fish/chinook-salmon.jpg",
    "images/fish/chinook-salmon/w01.jpg",
    "images/fish/chinook-salmon/w02.jpg",
    "images/fish/chinook-salmon/w03.jpg",
    "images/fish/chinook-salmon/w04.jpg"
  ],
  "coho-salmon": [
    "images/fish/coho-salmon.jpg",
    "images/fish/coho-salmon/w01.png",
    "images/fish/coho-salmon/w02.png",
    "images/fish/coho-salmon/w03.jpg",
    "images/fish/coho-salmon/w04.png"
  ],
  "pacific-salmon": [
    "images/fish/pacific-salmon.jpg",
    "images/fish/pacific-salmon/w01.jpg",
    "images/fish/pacific-salmon/w02.jpg",
    "images/fish/pacific-salmon/w03.jpg",
    "images/fish/pacific-salmon/w04.jpg"
  ],
  "walleye": [
    "images/fish/walleye.jpg",
    "images/fish/walleye/w01.jpg",
    "images/fish/walleye/w02.jpg",
    "images/fish/walleye/w03.jpg",
    "images/fish/walleye/w04.jpg"
  ],
  "yellow-perch": [
    "images/fish/yellow-perch.jpg",
    "images/fish/yellow-perch/w01.jpg",
    "images/fish/yellow-perch/w02.jpg",
    "images/fish/yellow-perch/w03.jpg",
    "images/fish/yellow-perch/w04.jpg"
  ],
  "northern-pike": [
    "images/fish/northern-pike.jpg",
    "images/fish/northern-pike/w01.jpg",
    "images/fish/northern-pike/w02.jpg",
    "images/fish/northern-pike/w03.jpg",
    "images/fish/northern-pike/w04.jpg"
  ],
  "muskellunge": [
    "images/fish/muskellunge.jpg",
    "images/fish/muskellunge/w01.jpg",
    "images/fish/muskellunge/w02.jpg",
    "images/fish/muskellunge/w03.jpg",
    "images/fish/muskellunge/w04.jpg"
  ],
  "lake-whitefish": [
    "images/fish/lake-whitefish.jpg",
    "images/fish/lake-whitefish/w01.jpg",
    "images/fish/lake-whitefish/w02.jpg",
    "images/fish/lake-whitefish/w03.jpg",
    "images/fish/lake-whitefish/w04.jpg"
  ],
  "cisco": [
    "images/fish/cisco.jpg",
    "images/fish/cisco/w01.jpg",
    "images/fish/cisco/w02.jpg",
    "images/fish/cisco/w03.jpg",
    "images/fish/cisco/w04.jpg"
  ],
  "sunfish": [
    "images/fish/sunfish.jpg",
    "images/fish/sunfish/w01.jpg",
    "images/fish/sunfish/w02.jpg",
    "images/fish/sunfish/w03.jpg",
    "images/fish/sunfish/w04.jpg"
  ],
  "crappie": [
    "images/fish/crappie.jpg",
    "images/fish/crappie/u01.jpg",
    "images/fish/crappie/u02.jpg",
    "images/fish/crappie/u03.jpg",
    "images/fish/crappie/u04.jpg",
    "images/fish/crappie/u05.jpg"
  ],
  "channel-catfish": [
    "images/fish/channel-catfish.jpg",
    "images/fish/channel-catfish/w01.jpg",
    "images/fish/channel-catfish/w02.jpg",
    "images/fish/channel-catfish/w03.jpg",
    "images/fish/channel-catfish/w04.jpg"
  ],
  "lake-sturgeon": [
    "images/fish/lake-sturgeon.jpg",
    "images/fish/lake-sturgeon/w01.png",
    "images/fish/lake-sturgeon/w02.jpg",
    "images/fish/lake-sturgeon/w03.jpg",
    "images/fish/lake-sturgeon/w04.jpg"
  ]
};
